# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17-oI5WpphSpIRRWu-PnW6m7zCBK0lDKV
"""

from google.colab import drive
drive.mount('/content/drive')

#@title Add direct download link
link = "" #@param {type:"string"}
import os
os.chdir("/content/drive/MyDrive/Downloads")
!wget -c {link} --no-check-certificate